### ISSUE TITLE
Element stay hidden, animation won't trigger when going to page through <NuxtLink />

### ISSUE THREAD

**Issue by jovylle** [mciastek/sal#105]
I'm using NuxtJs
I do have issue. the animation triggers normally when reloading.
But when accessing the page through ` <NuxtLink  /> ` the animation wont trigger and makes the element invisible (opacity:0)

**Comment by kisa777zaika** [comment]
I have the same problem using Nuxt.

**Comment by jovylle** [comment]
> 

I did find a fix, just put the sal() on mounted of every component/page that uses the effecst.
