### ISSUE TITLE
SyntaxError: Unexpected keyword 'export'

### ISSUE THREAD

**Issue by philharmonie** [mciastek/sal#18]
I'm getting this issue when I apply sal.js to my project.
I included the file in the header and run sal(); in the header as well.

https://github.com/mciastek/sal/blob/3833c57dab9f754b4474539d88873062e24c17f0/src/sal.js#L161

**Comment by mciastek** [comment]
How do you include sal.js library to your project?

**Comment by mciastek** [comment]
Due to inactivity I'm closing this issue. Please reopen if needed.
