### ISSUE TITLE
Jumpy Bug

### ISSUE THREAD

**Issue by QJan84** [mciastek/sal#21]
I found a bug! The bug can also be seen on the demo website: https://mciastek.github.io/sal/

Once an item reaches the top / bottom of the screen, the class ".sal-animation" is added and removed in a loop. This causes the item to fade in and out over and over again.

The bug is not always visible. Seemingly only at a certain scroll position.

**Comment by mciastek** [comment]
Unfortunately, it's related to how IntersectionObserver works. Basically, it checks if any pixel of the observed element is present in viewport. This means that if you move the element by some pixel below the threshold, but it's still in viewport it falls into animation loop. The one way to avoid it is to attach observer to element's parent, so the position of observed stays the same. This bug affects only transform based animation. I'm open to any suggestions how to resolve this bug.

It duplicates #3, so I'm closing this issue. Please leave comment in related issue.
