### ISSUE TITLE
Fire many animations at the same time

### ISSUE THREAD

**Issue by julianfox** [mciastek/sal#24]
Is it possible to fire many animations in the same time?
For example: fade and slide-up like in this website: https://www.runhunters.app/

**Comment by mciastek** [comment]
Yeah, that's how sal.js works. For combining transitions, you can declare your own animation like https://github.com/mciastek/sal/blob/a0a0e4f38a2896dffb7dd22f12052f77ac6af2c0/src/sal.scss#L98-L106
and play this animation when specific element gets `sal-animate` class like https://github.com/mciastek/sal/blob/a0a0e4f38a2896dffb7dd22f12052f77ac6af2c0/src/sal.scss#L120-L124

Regarding your example I think that `slide-up` animation is something you're looking for.

Let me know if this answers your question.

**Comment by mciastek** [comment]
Closing this issue. Please reopen in case of following questions.
