### ISSUE TITLE
Responsively change settings

### ISSUE THREAD

**Issue by mintymatt** [mciastek/sal#26]
How would you recommend changing Sal options responsively?

For example, changing the threshold for mobile VS desktop using Bootstrap grid sizes.

I would write my own screen width resize handler with debounce and passive options, but I cannot see a way in your documentation to re-create or reset Sal?

Many thanks!

**Comment by mciastek** [comment]
Hi, unfortunately sal.js doesn't support changing options responsively, out of the box. I'll add it to the roadmap and release it in the next version. Here's a walk-around for now - https://codesandbox.io/s/wizardly-newton-o8k3v

**Comment by pixedd** [comment]
Hey there, have you any news on this feature :) ?

**Comment by mciastek** [comment]
I added a new method, called `reset` (see [API](https://github.com/mciastek/sal#api) for reference). I'm closing this issue in favour of #31.
