### ISSUE TITLE
Another polyfill to add for older browsers

### ISSUE THREAD

**Issue by brentrobbins** [mciastek/sal#34]
Thanks for this create library. It works great! 

I am using it for a project that requires IE11 support, so following your note I added the Intersection Observer polyfill. That did fix the Intersection Observer, however IE11 was also triggering an error for the CustomEvent. So I found a nice polyfill for that (https://github.com/kumarharsh/custom-event-polyfill) which did the trick. So I propose adding another note for this polyfill to help support older browsers.

**Comment by mciastek** [comment]
Looks like a great idea. I think that the best place to include information about polyfill is [Events](https://github.com/mciastek/sal#events) section in docs. What do you think?

**Comment by brentrobbins** [comment]
Hi @mciastek that's exactly where I was thinking too.
