### ISSUE TITLE
Mobile: boolean

### ISSUE THREAD

**Issue by igorgarciaco** [mciastek/sal#37]
Hi, some components are not showing up on mobile browser can I disable it like "mobile: false" in options?

**Comment by mciastek** [comment]
Hi, there's no such option in sal. Honestly, I'm not sure if I understand your requirement. Could you create a simple example using [Codesandbox](https://codesandbox.io/s/vanilla)?

**Comment by igorgarciaco** [comment]
Well I was just wondering if it has an option for mobile like this https://scrollrevealjs.org/api/mobile.html

**Comment by mciastek** [comment]
Ah, I see. Unfortunately there is no such option in sal.js, but you can easily make it work, wrapping sal's initialisation in `if` block. Here's an example:

```js

// filched from https://github.com/jlmakes/scrollreveal/blob/master/src/utils/is-mobile.js
// though it may be too weak condition,
// better use https://github.com/juliangruber/is-mobile
const isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);

if (!isMobile) {
  sal(); // init sal.js only for non-mobile devices
}
```

This code will initialise sal only for non-mobile devices. Let me know if that's what you've been looking for.

**Comment by mciastek** [comment]
Closing this issue. Reopen if needed.
