### ISSUE TITLE
Support individual target animation repeat

### ISSUE THREAD

**Issue by allaire** [mciastek/sal#45]
I would like to be able to have animations running once on almost every elements, except some. Currently, the `once` option is global. What about supporting an individual option (via data attributes) for specific elements?

Something like `<div data-sal="fade" data-sal-repeat></div>`

```js
const onIntersection = (entries, observer) => {
  entries.forEach(entry => {
    if (entry.intersectionRatio >= options.threshold) {
      animate(entry);

      if (options.once && entry.target.dataset.salRepeat === undefined) {
        observer.unobserve(entry.target);
      }
    } else if (!options.once || entry.target.dataset.salRepeat !== undefined) {
      reverse(entry);
    }
  });
};
```

**Comment by mciastek** [comment]
I this enhancement 👍 Would you like to create a PR with it?

**Comment by jesserosenfield** [comment]
Or alternatively `[data-sal-once]` HTML attribute

Thanks for the amazing plugin!
