### ISSUE TITLE
Conflict with CSS transition

### ISSUE THREAD

**Issue by filipchrapek** [mciastek/sal#46]
Hi Mirek,

so I have some custom transitions set and it seems that I cannot use your library together with my css on the same element. What I did is that I added extra div and one element is for my css and the second is for sal.js.

Is there a different fix for this?

**Comment by mciastek** [comment]
I'm afraid that there's any only way to do it. It's related to how CSS works. So if you want to add any extra transition to element animated by sal.js you need to wrap this element into a container. Remember that sal.js uses Intersection Observer, so if you move container outside viewport using translate observer probably can have issues with tracking your animated element.

**Comment by filipchrapek** [comment]
Ok, got it. Appreciate the fast response.
