### ISSUE TITLE
Does not work in ie

### ISSUE THREAD

**Issue by drnkwati** [mciastek/sal#5]
Hi 
Cool library but ie is not supported

**Comment by mciastek** [comment]
Hi, thanks for the comment. Can you provide more details about the browser that you used?

**Comment by drnkwati** [comment]
I tried in ie9 and 10 but get errors in console.

**Comment by mciastek** [comment]
Ah, ok. IE 9 and 10 is not supported by default. If you take a look on [caniuse](https://caniuse.com/#feat=intersectionobserver), you will see that [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is supported by IE Edge 15+. There's is a PR, which provides an information about [polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) (see: https://github.com/mciastek/sal/pull/4).

Due the limited support of `IntersectionObserver` in IE 9+, I'm closing this issue.
