### ISSUE TITLE
Horizontal Scroll Bar on mobile

### ISSUE THREAD

**Issue by Cpaczek** [mciastek/sal#53]
Hello,

Currently have this install on my website with some slide and flip animations and it is causing a horizontal scrollbar to appear only on mobile. I have the "once" property set to true meaning after I scroll down all the way and load all of the animations the scrollbar goes away. Is there some css styling I have to have? or is this a bug with sal.js

**Comment by mciastek** [comment]
Probably, some element is exceeding window's boundaries. Even if you apply transform to element, it can expand browser's window causing horizontal scroll to appear. Try to add `overflow: hidden;` to container with animations. Let me know if it solves your problem.

**Comment by Cpaczek** [comment]
I was able to figure out which one is causing it and it's an image that I have on the site, I am using bulma and it's in a column but adding overflow hidden to both the animation div or the child div doesn't do anything

`                    <div data-sal="slide-left" >
                        <div class="column is-6" style="overflow: hidden;"><img src="../assets/faux-code.png" alt=""></div>
                    </div>`

**Comment by mciastek** [comment]
You should add `overflow: hidden` to parent of `<div data-sal="slide-left">`. If you need some assistance, please create a demo using [Codesandbox](https://codesandbox.io/s/vanilla). It will help us with debugging.

**Comment by Cpaczek** [comment]
Thanks that fixed it.
