### ISSUE TITLE
Animated elements auto hides

### ISSUE THREAD

**Issue by seeratawan01** [mciastek/sal#63]
i'm using sal.js in gridsome (vue.js) application, when an event fires siblings animated elements automatically hides

**Comment by mciastek** [comment]
Could you provide a simple working example using some of the available online IDEs like [CodeSandbox](https://codesandbox.io/)?

**Comment by dealenx** [comment]
Why is this issue closed?

The problem is still relevant.

CodeSandBox: https://codesandbox.io/s/nuxt-with-sal-js-c35g2
