### ISSUE TITLE
Plugin not working in an angular application

### ISSUE THREAD

**Issue by BIINBELLLO** [mciastek/sal#64]
I installed the plugin as directed in the readme file. 

I initially included the css and js files in the angular.json file, but for some reason it was not seeing it, complains about Sal not defined.

I then copied the entire sal.js folder from my node_modules folder into my assets folder and linked to the files from my index.html file, it now finds it, but when I add the data-sal attribute to any element, using either fade, slide-up or any other value, the element disappears from the screen, 

On inspecting I realized the data-sal somewhere in the scss turns the opacity of the element to 0, if I manually change it, the animation does not work.

Help please...
![Screenshot_1](https://user-images.githubusercontent.com/22405338/97119697-2efb3f80-1712-11eb-9d3d-b94bdaa1634b.png)

**Comment by mciastek** [comment]
It looks like the element is not animated. As you can see in the [code] (https://github.com/mciastek/sal/blob/master/src/sal.scss#L143-L147) any element `data-sal="zoom"` and `.sal-animate` gets `opacity: 1;`. Please check if element is visible in the viewport.

**Comment by quantumleap33** [comment]
Solved, I had to include the init file in the body.

`wp_enqueue_script( 'sal-init', get_stylesheet_directory_uri() . '/sal/sal-init.js', '', '', true );`

Thank you.
