### ISSUE TITLE
Multiple animations

### ISSUE THREAD

**Issue by quantumleap33** [mciastek/sal#69]
Is there a way to apply multiple `data-sal` animations? `fade slide-right`, for example.

**Comment by mciastek** [comment]
No, there's not support for that. If you want to make a custom animation, by combining fade and slide-right, you can define your own animation class and use an empty `data-sal` attribute to trigger animation. For example:

```html
<div data-sal class="custom-animation"></div>
```

```scss
.custom-animation {
  // default styles
}

.custom-animation.sal-animate {
  // styles for animation
}
```

**Comment by soumakdev** [comment]
Please add this example in docs, it might be helpful to others
