### ISSUE TITLE
Is there a CDN for Sal.js?

### ISSUE THREAD

**Issue by Jordakoes** [mciastek/sal#71]
I was wondering if there's any way I can install Sal.js using a CDN instead of installing it with NPM.
Let me know! :)

**Comment by Jordakoes** [comment]
Mitigated this by downloading the Repo and linking to /sal.js and /sal.css instead of using a CDN.

**Comment by mciastek** [comment]
You can use UNPKG, for example:

- https://unpkg.com/sal.js@0.8.2/dist/sal.js -> JS file
- https://unpkg.com/sal.js@0.8.2/dist/sal.css -> stylesheet
