### ISSUE TITLE
Elements are animated in but are invisible.

### ISSUE THREAD

**Issue by Jordakoes** [mciastek/sal#72]
On my Shopify collection page, as the user scrolls down products get loaded into the DOM. These products however, stay hidden when I try to animate them with Sal.js. I previously used AOS where this problem did not occur _(looking to change to Sal since I am experiencing some weird bugs under iOS14 with AOS)._

I uploaded a Gif of the problem [here](https://gph.is/g/ZyWNwBb)

**Comment by mciastek** [comment]
The gif is a bit small 🔍 , but I managed to notice the problem. I think it happens, because the list with items is dynamically expanded. When you make a sal's instance it reads elements that are currently on the page.

https://github.com/mciastek/sal/blob/98d0ad3415dc235281a8a320b306af930f6b03a7/src/sal.js#L173-L178

With current API it's not possible to update a list of animated elements, so sal won't know that it needs to animate new elements. I'll provide a method that help with this issue.

**Comment by Jordakoes** [comment]
Cool! Good to hear you know where the problem comes from. Any update on the method to help fix the issue?

**Comment by Jordakoes** [comment]
I noticed that the products getting loaded into the DOM are not getting the 'sal-animate' class (image [here](https://imgur.com/a/ZgQDCuo)) If I manually add the class, they do animate in perfectly. Any idea on how to mitigate this?

**Comment by mciastek** [comment]
I created a PR with new method - #73. Let me run some tests and it will be good to go. Stay tuned.

**Comment by Jordakoes** [comment]
Cool! Let me know when it's ready for me to use 😄

**Comment by Levdbas** [comment]
@mciastek , I am willing to test this on one of my current projects where I also need this feature. If you can publish a test/rc version I can test this pretty soon.

**Comment by mciastek** [comment]
@Jordakoes I pushed new version 0.8.3 that adds `update()` method. Please check if it's useful for your case.

**Comment by Jordakoes** [comment]
@mciastek Thankyou. I have updated to sal 0.8.3 and have change my init code to:
`<script>
    const scrollAnimations = sal({
      threshold: .5,
    });
    scrollAnimations.update({
      selector: 'grid__item',
    });
  </script>`

However, on the Collection page the 'new' elements don't animate in. When I run sal().update in the browsers console, it causes the items to animate in beautifully. Feel like I am using the Method wrong. Any pointers?

**Comment by Jordakoes** [comment]
Had some issues getting it to work since I didn't know where to call the `update()` method. Did some digging where the new elements got loaded into the DOM, added the method and it works butterly smooth now. Amazing work @mciastek, thanks a bunch!

**Comment by Levdbas** [comment]
I got success as well! Tnx @mciastek
