### ISSUE TITLE
Feature Request: Passing element as node or root element option

### ISSUE THREAD

**Issue by davidbwaters** [mciastek/sal#74]
Hi, I'd like to use this with Shadow DOM and would like the option to set the root node of the observer or the ability to pass a list of elements as an alternative to the current string selector option and just type check on init.  I know Intersection Observer has a root option also, but which would work.  I think IO on the body penetrates shadow DOM, so passing elements would probably work best.

**Comment by mciastek** [comment]
Hey @davidbwaters, I added feature you requested. You can use `root` option. See [documentation](https://github.com/mciastek/sal#advanced-options) for more details.

**Comment by davidbwaters** [comment]
Wow, great support.  Thanks.
