### ISSUE TITLE
How to create custom animations?

### ISSUE THREAD

**Issue by Jordakoes** [mciastek/sal#80]
I've seen [websites](https://faizur.com) use sal with custom animations (eg: something else than available from stock; fade, slide-in). How would I go about creating my own animation?

Let's say I want to create an animation called _'subtleFade'_. I'd want to call it giving an element the data attribute '`data-sal-subtleFade`'.

Let me know! 🙌🏻

**Comment by Jordakoes** [comment]
Bump? 🤔

**Comment by mciastek** [comment]
Please refer to https://github.com/mciastek/sal/issues/17#issuecomment-480833686. Cheers!
